'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {unitArt} from '@/lib/game/unit-art';
import {SPECS,alive,canPlace,effectiveRange} from '@/lib/game/engine';
import type {Game,Point,Kind} from '@/lib/game/engine';
import {DISPUTED_BOUNDARIES,REGION_LABELS,HURDLES,clipPolyline} from '@/lib/game/cartography';
import {renderPosition} from '@/lib/game/motion';
import {emptyStock} from '@/lib/game/maintenance';
import {recentAlerts} from '@/lib/game/alerts';
import {tacticalDistance,engagementDistance} from '@/lib/game/world';
import {terrainHeight,elevationAt,RIVERS,BARRIER_SEGMENTS,TERRAIN_BOUNDS} from '@/lib/game/terrain';
import {flightPosition,followPosition} from '@/lib/game/camera';
import type {FollowTarget} from '@/lib/game/camera';
import geography from '../public/south-asia.json';
type Props={g:Game;selected:number[];placing:Kind|null;view:{x:number;y:number;w:number;h:number};follow:FollowTarget|null;pan:boolean;offset:number;layers:{friendly:boolean;contacts:boolean;coverage:boolean;supply:boolean;terrain:boolean};onSelect:(ids:number[],additive:boolean)=>void;onTarget:(id:number)=>void;onMap:(p:Point,append:boolean)=>void;onCrossing:(id:string)=>void;onCivilian:(id:string)=>void;onFallback:()=>void;onViewSnapshot?:(view:{x:number;y:number;w:number;h:number})=>void};
export default function TerrainView(props:Props){const mount=useRef<HTMLDivElement>(null),latest=useRef(props),[error,setError]=useState(''),[box,setBox]=useState<{x:number;y:number;w:number;h:number}|null>(null);latest.current=props;const rig=useRef<{camera:THREE.PerspectiveCamera;controls:OrbitControls}|null>(null);
 useEffect(()=>{const r=rig.current;if(!r)return;const p={x:props.view.x+props.view.w/2,y:props.view.y+props.view.h/2},h=Math.max(0,terrainHeight(p));r.controls.target.set(p.x,h,p.y);r.camera.position.set(p.x,Math.max(36,props.view.w*.66)+h,p.y+props.view.h*.48);r.controls.update();},[props.view]);
 useEffect(()=>{const el=mount.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('3D terrain is unavailable on this device. The command map remains fully playable.');return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#7898a5');el.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.fog=new THREE.Fog('#8ba9b4',1000,2400);scene.add(new THREE.HemisphereLight('#e2eff5','#756650',2.2));const sun=new THREE.DirectionalLight('#fff0d4',2.2);sun.position.set(-250,650,-400);scene.add(sun);const camera=new THREE.PerspectiveCamera(43,1,.5,4000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.minDistance=12;controls.maxDistance=1800;controls.maxPolarAngle=Math.PI*.455;controls.minPolarAngle=.1;controls.screenSpacePanning=false;controls.mouseButtons={LEFT:undefined,MIDDLE:THREE.MOUSE.PAN,RIGHT:THREE.MOUSE.ROTATE};controls.touches={ONE:undefined,TWO:THREE.TOUCH.DOLLY_ROTATE};rig.current={camera,controls};const init=latest.current.view,p={x:init.x+init.w/2,y:init.y+init.h/2};controls.target.set(p.x,Math.max(0,terrainHeight(p)),p.y);camera.position.set(p.x,init.w*.66+60,p.y+init.h*.48);controls.update();
 const disposables:{dispose:()=>void}[]=[];const keep=<T extends {dispose:()=>void}>(a:T)=>{disposables.push(a);return a;};const loader=new THREE.TextureLoader();let active=true;const texture=keep(loader.load('/assets/terrain.webp',()=>{},undefined,()=>{if(active)terrainMat.map=null;}));texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();const terrainGeom=keep(new THREE.PlaneGeometry(TERRAIN_BOUNDS.width,TERRAIN_BOUNDS.height,320,288));terrainGeom.rotateX(-Math.PI/2);terrainGeom.translate(594,0,561);const position=terrainGeom.attributes.position;for(let i=0;i<position.count;i++)position.setY(i,terrainHeight({x:position.getX(i),y:position.getZ(i)}));terrainGeom.computeVertexNormals();const terrainMat=keep(new THREE.MeshStandardMaterial({map:texture,roughness:1,metalness:0}));const terrain=new THREE.Mesh(terrainGeom,terrainMat);scene.add(terrain);const water=new THREE.Mesh(keep(new THREE.PlaneGeometry(3500,3500)),keep(new THREE.MeshPhongMaterial({color:'#235975',transparent:true,opacity:.84,shininess:75,depthWrite:false})));water.rotation.x=-Math.PI/2;water.position.set(528,.4,561);scene.add(water);
 function line(points:THREE.Vector3[],color:THREE.ColorRepresentation,opacity=.6,dashed=false){const geometry=keep(new THREE.BufferGeometry().setFromPoints(points));const material=keep(dashed?new THREE.LineDashedMaterial({color,transparent:true,opacity,dashSize:4,gapSize:4}):new THREE.LineBasicMaterial({color,transparent:true,opacity}));const object=new THREE.Line(geometry,material);if(dashed)object.computeLineDistances();scene.add(object);return object;}
 const meshHeight=(p:Point)=>{const gx=Math.max(0,Math.min(319.999,(p.x+66)/1320*320)),gy=Math.max(0,Math.min(287.999,(p.y+33)/1188*288)),ix=Math.floor(gx),iy=Math.floor(gy),tx=gx-ix,ty=gy-iy,a=position.getY(iy*321+ix),b=position.getY(iy*321+ix+1),c=position.getY((iy+1)*321+ix),d=position.getY((iy+1)*321+ix+1);return tx+ty<=1?a+(b-a)*tx+(c-a)*ty:d+(c-d)*(1-tx)+(b-d)*(1-ty);};
 const drape=(p:Point,extra=1.5)=>new THREE.Vector3(p.x,Math.max(.5,meshHeight(p))+extra,p.y);
 for(const r of RIVERS)for(const points of clipPolyline(r.points))line(points.map(p=>drape(p,1.4)),'#81c7dd',.72);
 for(const s of BARRIER_SEGMENTS)line([drape(s.a,2.2),drape(s.b,2.2)],'#f5ca76',.9);
 for(const country of geography.features){const polygons=country.geometry.type==='Polygon'?[country.geometry.coordinates]:country.geometry.coordinates;for(const polygon of polygons as number[][][][])for(const ring of polygon)for(const points of clipPolyline(ring.map(([lon,lat])=>({x:(lon-60)*33,y:(39-lat)*33}))))line(points.map(p=>drape(p,2)),'#f2ddac',.35,true);}
 for(const b of DISPUTED_BOUNDARIES)line(b.points.map(p=>drape(p,3)),b.kind==='loc'?'#ffe0a3':'#eee4d2',.9,true);
 // Marching contour segments sampled from the bundled elevation grid.
 const contourVertices:number[]=[];const grid=96,stepX=1320/grid,stepY=1188/grid;for(let y=0;y<grid;y++)for(let x=0;x<grid;x++){const ps=[{x:-66+x*stepX,y:-33+y*stepY},{x:-66+(x+1)*stepX,y:-33+y*stepY},{x:-66+(x+1)*stepX,y:-33+(y+1)*stepY},{x:-66+x*stepX,y:-33+(y+1)*stepY}],hs=ps.map(elevationAt);for(const level of [500,1000,2000,3000,4500]){const hits:Point[]=[];for(let e=0;e<4;e++){const j=(e+1)%4;if((hs[e]<level)!==(hs[j]<level)){const t=(level-hs[e])/(hs[j]-hs[e]);hits.push({x:ps[e].x+(ps[j].x-ps[e].x)*t,y:ps[e].y+(ps[j].y-ps[e].y)*t});}}for(let i=1;i<hits.length;i+=2)for(const p of [hits[i-1],hits[i]])contourVertices.push(p.x,meshHeight(p)+1.5,p.y);}}
 const contourGeom=keep(new THREE.BufferGeometry());contourGeom.setAttribute('position',new THREE.Float32BufferAttribute(contourVertices,3));const contours=new THREE.LineSegments(contourGeom,keep(new THREE.LineBasicMaterial({color:'#f6e4b8',transparent:true,opacity:.17})));scene.add(contours);
 const atlas=keep(loader.load('/assets/unit-atlas.png',()=>{for(const d of disposables)if(d instanceof THREE.Texture)d.needsUpdate=true;})),newAtlas=keep(loader.load('/assets/new-units.png',()=>{for(const d of disposables)if(d instanceof THREE.Texture)d.needsUpdate=true;}));atlas.colorSpace=newAtlas.colorSpace=THREE.SRGBColorSpace;
 function crop(index:number,isNew=false){const base=isNew?newAtlas:atlas,tex=keep(base.clone()),cols=isNew?3:6,rows=isNew?2:4;tex.repeat.set(1/cols,1/rows);tex.offset.set(index%cols/cols,1-(Math.floor(index/cols)+1)/rows);tex.needsUpdate=true;return tex;}
 const matCache=new Map<string,THREE.MeshBasicMaterial>();function unitMaterial(kind:Kind,enemy:boolean){const key=kind+enemy;if(!matCache.has(key)){if(kind==='industry'){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d')!;c.fillStyle=enemy?'#b88876':'#839778';c.strokeStyle='#ece0b5';c.lineWidth=3;c.beginPath();c.moveTo(12,108);c.lineTo(12,48);c.lineTo(40,28);c.lineTo(40,48);c.lineTo(74,28);c.lineTo(74,108);c.closePath();c.fill();c.stroke();c.fillRect(88,10,20,98);c.strokeRect(88,10,20,98);c.fillStyle='#e6dcb1';for(const x of [22,51])for(const y of [62,84])c.fillRect(x,y,12,8);const map=keep(new THREE.CanvasTexture(canvas));matCache.set(key,keep(new THREE.MeshBasicMaterial({map,transparent:true,alphaTest:.12,side:THREE.DoubleSide,depthWrite:false})));return matCache.get(key)!;}const art=unitArt(kind)??unitArt('airfield')!,tex=keep((art.path.includes('new-units')?newAtlas:atlas).clone());tex.repeat.set(art.width/1536,art.height/1024);tex.offset.set(art.x/1536,1-(art.y+art.height)/1024);tex.needsUpdate=true;matCache.set(key,keep(new THREE.MeshBasicMaterial({map:tex,transparent:true,alphaTest:.12,color:enemy?'#ffc7ba':'#ffffff',side:THREE.DoubleSide,depthWrite:false})));}return matCache.get(key)!;}
 function textLabel(text:string,color='#eef7f8'){const c=document.createElement('canvas');c.width=512;c.height=64;const ctx=c.getContext('2d')!;ctx.font='600 24px system-ui';ctx.textAlign='center';ctx.fillStyle='#142730cc';ctx.fillRect(0,0,512,64);ctx.fillStyle=color;ctx.fillText(text,256,40);const texture=keep(new THREE.CanvasTexture(c));const sprite=new THREE.Sprite(keep(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false})));sprite.scale.set(84,10.5,1);return sprite;}
 for(const [text,p] of [['HIMALAYAS',{x:620,y:150}],['ARABIAN SEA',{x:230,y:740}],['INDIA',{x:740,y:640}],['PAKISTAN',{x:240,y:275}]] as [string,Point][]){const label=textLabel(text,'#e9e1c7');label.position.copy(drape(p,18));scene.add(label);}
 for(const r of REGION_LABELS){const label=textLabel(r.name,'#ffe1b4');label.position.copy(drape(r,10));scene.add(label);}
 const obstacleMesh=new THREE.Group();for(const h of HURDLES){const pts=[{x:h.x,y:h.y},{x:h.x+20,y:h.y},{x:h.x+20,y:h.y+20},{x:h.x,y:h.y+20},{x:h.x,y:h.y}];const mark=line(pts.map(p=>drape(p,2.5)),h.elevation>5100?'#efa080':'#eed28e',.24);obstacleMesh.add(mark);}scene.add(obstacleMesh);
 const unitGeom=keep(new THREE.PlaneGeometry(32,32));const ringGeom=keep(new THREE.RingGeometry(17,18,32));const markers=new Map<number,{group:THREE.Group;model:THREE.Mesh;ring:THREE.Mesh;label:THREE.Sprite;stock:THREE.Sprite;kind:Kind;known:boolean}>();const paths=new THREE.Group();scene.add(paths);const effects=new THREE.Group();scene.add(effects);const sectorObjects=latest.current.g.theatre.sectors.map(s=>{const pts=[{x:s.x-49,y:s.y-46},{x:s.x+49,y:s.y-46},{x:s.x+49,y:s.y+46},{x:s.x-49,y:s.y+46},{x:s.x-49,y:s.y-46}];const border=line(pts.map(p=>drape(p,2.3)),'#d1bc83',.65);const label=textLabel(s.name);label.scale.set(72,9,1);label.position.copy(drape({x:s.x,y:s.y-41},7));scene.add(label);const capture=line(Array.from({length:49},(_,i)=>drape({x:s.x+Math.cos(i/48*Math.PI*2)*tacticalDistance(58),y:s.y+Math.sin(i/48*Math.PI*2)*tacticalDistance(58)},3)),'#d1bc83',.8,true);return{border,label,capture};});
 const crossings=latest.current.g.theatre.crossings.map(c=>{const model=new THREE.Mesh(keep(new THREE.PlaneGeometry(24,34)),keep(new THREE.MeshBasicMaterial({map:crop(4,true),transparent:true,alphaTest:.15,side:THREE.DoubleSide})));model.rotation.x=-Math.PI/2;model.position.copy(drape(c,2.8));model.userData={type:'crossing',id:c.id};scene.add(model);const label=textLabel(c.name);label.position.copy(drape(c,11));scene.add(label);return {model,label};});
 const civilians=latest.current.g.theatre.civilians.map(c=>{const model=new THREE.Mesh(keep(new THREE.PlaneGeometry(28,28)),keep(new THREE.MeshBasicMaterial({map:crop(5,true),transparent:true,alphaTest:.15,side:THREE.DoubleSide})));model.rotation.x=-Math.PI/2;model.position.copy(drape(c,2));model.userData={type:'civilian',id:c.id};scene.add(model);const label=textLabel(c.name,'#c6dcf7');label.position.copy(drape(c,10));scene.add(label);return{model,label};});
 const deployment=new THREE.Mesh(keep(new THREE.RingGeometry(25,27,48)),keep(new THREE.MeshBasicMaterial({color:'#eac383',transparent:true,opacity:.9,side:THREE.DoubleSide})));deployment.rotation.x=-Math.PI/2;deployment.visible=false;scene.add(deployment);const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let down:{x:number;y:number;append:boolean;select:boolean}|null=null;const touches=new Set<number>();let gesture=false;let hovered:Point|null=null;
 function ray(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);}
 const alphaCache=new WeakMap<object,{data:Uint8ClampedArray;width:number;height:number}>();
 function opaqueHit(hit:THREE.Intersection){if(!hit.uv||!(hit.object instanceof THREE.Mesh))return true;const mat=hit.object.material as THREE.MeshBasicMaterial,tex=mat.map,img=tex?.image as HTMLImageElement|undefined;if(!tex||!img?.width)return true;try{let cached=alphaCache.get(img);if(!cached){const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(img,0,0);cached={data:ctx.getImageData(0,0,img.width,img.height).data,width:img.width,height:img.height};alphaCache.set(img,cached);}tex.updateMatrix();const uv=tex.transformUv(hit.uv.clone()),x=Math.min(cached.width-1,Math.max(0,Math.floor(uv.x*cached.width))),y=Math.min(cached.height-1,Math.max(0,Math.floor(uv.y*cached.height)));return cached.data[(y*cached.width+x)*4+3]>24;}catch{return true;}}
 function ground(e:PointerEvent){ray(e);const hit=raycaster.intersectObjects([terrain,water],false)[0];return hit?{x:hit.point.x,y:hit.point.z}:null;}
 const pointerDown=(e:PointerEvent)=>{if(e.button!==0)return;if(e.pointerType==='touch'){touches.add(e.pointerId);if(touches.size>1){gesture=true;down=null;setBox(null);controls.enabled=true;return;}}down={x:e.clientX,y:e.clientY,append:e.shiftKey,select:!latest.current.pan||e.metaKey||e.ctrlKey};if(down.select&&e.pointerType!=='touch')controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);};
 const pointerMove=(e:PointerEvent)=>{if(gesture)return;hovered=ground(e);if(down&&down.select&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6){const r=renderer.domElement.getBoundingClientRect();setBox({x:Math.min(e.clientX,down.x)-r.left,y:Math.min(e.clientY,down.y)-r.top,w:Math.abs(e.clientX-down.x),h:Math.abs(e.clientY-down.y)});}};
 const pointerUp=(e:PointerEvent)=>{if(e.pointerType==='touch')touches.delete(e.pointerId);if(gesture){if(!touches.size)gesture=false;down=null;setBox(null);controls.enabled=true;return;}const d=down;down=null;setBox(null);controls.enabled=true;if(!d)return;const moved=Math.hypot(e.clientX-d.x,e.clientY-d.y)>6,q=latest.current;if(moved){if(!d.select)return;const r=renderer.domElement.getBoundingClientRect(),ids:number[]=[];for(const u of alive(q.g,'india')){if(!q.layers.friendly||!SPECS[u.kind].speed||SPECS[u.kind].structure)continue;const point=drape(u,SPECS[u.kind].air?24:3).project(camera),x=r.left+(point.x+1)*r.width/2,y=r.top+(1-point.y)*r.height/2;if(point.z<1&&x>=Math.min(d.x,e.clientX)&&x<=Math.max(d.x,e.clientX)&&y>=Math.min(d.y,e.clientY)&&y<=Math.max(d.y,e.clientY))ids.push(u.id);}q.onSelect(ids,d.append);return;}const p=ground(e);if(q.placing){if(p)q.onMap(p,e.shiftKey);return;}ray(e);const objects=[...Array.from(markers.values()).filter(m=>m.group.visible).map(m=>m.model),...crossings.filter(c=>c.model.visible).map(c=>c.model),...civilians.map(c=>c.model)];const terrainDistance=raycaster.intersectObjects([terrain,water],false)[0]?.distance??Infinity;const hit=raycaster.intersectObjects(objects,false).find(h=>h.distance<=terrainDistance+1&&opaqueHit(h))?.object.userData;if(hit){if(hit.type==='unit')hit.team==='india'?q.onSelect([hit.id],e.shiftKey):q.onTarget(hit.id);else if(hit.type==='crossing')q.onCrossing(hit.id);else q.onCivilian(hit.id);}else if(p)q.onMap(p,e.shiftKey);};
 const cancel=()=>{down=null;touches.clear();gesture=false;setBox(null);controls.enabled=true;};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',cancel);const lost=(e:Event)=>{e.preventDefault();setError('The 3D graphics context was interrupted. Return to the command map to continue.');};renderer.domElement.addEventListener('webglcontextlost',lost);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const clearDynamic=(group:THREE.Group)=>{for(const child of [...group.children]){if(child instanceof THREE.Line||child instanceof THREE.Mesh){child.geometry.dispose();const mats=Array.isArray(child.material)?child.material:[child.material];for(const m of mats)m.dispose();}group.remove(child);}};
 let raf=0,lastPaint=0,lastFollow:string|null=null;const followOffset=new THREE.Vector3(0,85,130);function animate(now:number){if(!active)return;const q=latest.current,g=q.g;controls.mouseButtons.LEFT=q.pan?THREE.MOUSE.PAN:undefined;controls.touches.ONE=q.pan?THREE.TOUCH.PAN:undefined;const focus=followPosition(g,q.follow,q.offset),focusKey=q.follow?JSON.stringify(q.follow):null;if(focus){const target=new THREE.Vector3(focus.x,focus.altitude,focus.y);if(lastFollow!==focusKey){followOffset.copy(camera.position).sub(controls.target).normalize().multiplyScalar(q.follow?.kind==='missile'?65:85);followOffset.y=Math.max(35,followOffset.y);}else followOffset.copy(camera.position).sub(controls.target);camera.position.copy(target).add(followOffset);controls.target.copy(target);}lastFollow=focusKey;
 if(now-lastPaint>40){lastPaint=now;const snapshotWidth=Math.max(20,Math.min(1800,camera.position.distanceTo(controls.target)*2*Math.tan(camera.fov*Math.PI/360)*camera.aspect));q.onViewSnapshot?.({x:controls.target.x-snapshotWidth/2,y:controls.target.z-snapshotWidth*q.view.h/q.view.w/2,w:snapshotWidth,h:snapshotWidth*q.view.h/q.view.w});for(const m of markers.values())m.group.visible=false;const visible=[...(q.layers.friendly?alive(g,'india'):[]).map(u=>({...u,identified:true})),...(q.layers.contacts?Object.values(g.contacts.india).map(c=>({...c,team:'pakistan' as const,identified:c.identified,hp:c.hp,heading:c.heading??0})):[])];for(const u of visible){let m=markers.get(u.id);if(m&&m.known!==u.identified){scene.remove(m.group);m.ring.material instanceof THREE.Material&&m.ring.material.dispose();markers.delete(u.id);m=undefined;}if(!m){const group=new THREE.Group();const model=new THREE.Mesh(unitGeom,u.identified?unitMaterial(u.kind,u.team==='pakistan'):keep(new THREE.MeshBasicMaterial({color:'#f5c8b9',wireframe:true,side:THREE.DoubleSide})));model.rotation.x=-Math.PI/2;model.userData={type:'unit',id:u.id,team:u.team};const ring=new THREE.Mesh(ringGeom,keep(new THREE.MeshBasicMaterial({color:u.team==='india'?'#7dd9b8':'#f09088',side:THREE.DoubleSide,transparent:true,opacity:.7})));ring.rotation.x=-Math.PI/2;const label=textLabel(u.identified?u.name:'Unidentified contact',u.team==='india'?'#d9f4e4':'#fbd1c4');label.position.set(0,14,0);const stock=textLabel('EMPTY · AUTO RESUPPLY','#ffc48b');stock.position.set(0,23,0);stock.scale.set(58,7,1);group.add(model,ring,label,stock);scene.add(group);m={group,model,ring,label,stock,kind:u.kind,known:u.identified};markers.set(u.id,m);}const pose=renderPosition(g,u,q.offset,u.team==='pakistan');m.stock.visible=u.team==='india'&&emptyStock(u as import('@/lib/game/engine').Unit);m.group.visible=true;m.group.position.copy(drape(pose,SPECS[u.kind].air?23:3));m.model.rotation.z=-((SPECS[u.kind].structure?0:pose.heading??0)+(unitArt(u.kind)?.correction??0))*Math.PI/180;const selected=q.selected.includes(u.id);m.ring.scale.setScalar(selected?1.25:1);(m.ring.material as THREE.MeshBasicMaterial).color.set(selected?'#ffe095':u.team==='india'?'#7dd9b8':'#f09088');m.label.visible=selected||SPECS[u.kind].structure;const stale=u.team==='pakistan'&&g.time-g.contacts.india[u.id].seen>1;const markerScale=Math.max(.2,Math.min(1,camera.position.distanceTo(m.group.position)/550));m.group.scale.setScalar(markerScale*(stale?.82:1));}
 for(let i=0;i<sectorObjects.length;i++){const s=g.theatre.sectors[i];(sectorObjects[i].capture.material as THREE.LineBasicMaterial).color.set(s.connected==='india'?'#67d9b3':s.connected==='pakistan'?'#ed8a83':'#eedca7');(sectorObjects[i].border.material as THREE.LineBasicMaterial).color.set(s.connected==='india'?'#67d9b3':s.connected==='pakistan'?'#ed8a83':'#eedca7');}
 for(let i=0;i<crossings.length;i++){const crossing=g.theatre.crossings[i],bridge=markers.get(crossing.assetId??-1);crossings[i].model.visible=!bridge?.group.visible;crossings[i].model.material.opacity=crossing.open?1:.4;crossings[i].label.visible=!bridge?.group.visible&&camera.position.distanceTo(crossings[i].model.position)<500;}
 for(let i=0;i<civilians.length;i++){civilians[i].model.material.color.set(g.theatre.civilians[i].panic>40?'#ffd7a1':'#ffffff');civilians[i].label.visible=camera.position.distanceTo(civilians[i].model.position)<420;}
 clearDynamic(paths);for(const u of alive(g,'india').filter(u=>q.selected.includes(u.id))){if(u.path.length||u.queue.length){const geo=new THREE.BufferGeometry().setFromPoints([u,...u.path,...u.queue].map(p=>drape(p,SPECS[u.kind].air?24:4)));paths.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#ffe09b'})));}if(q.layers.coverage&&['s400','akash','counterdrone'].includes(u.kind)){const ps=Array.from({length:65},(_,i)=>drape({x:u.x+effectiveRange(g,u)*Math.cos(i/64*Math.PI*2),y:u.y+effectiveRange(g,u)*Math.sin(i/64*Math.PI*2)},3));paths.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps),new THREE.LineBasicMaterial({color:'#8ce7cd',transparent:true,opacity:.6})));}}
 clearDynamic(effects);for(const m of g.missiles){if(m.team!=='india'&&!alive(g,'india').some(u=>Math.hypot(u.x-m.to.x,u.y-m.to.y)<100))continue;const p=flightPosition(m,q.offset),points=Array.from({length:12},(_,i)=>flightPosition({...m,age:Math.max(0,m.age+q.offset-i*.055)},0)).map(p=>new THREE.Vector3(p.x,p.altitude,p.y));effects.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:m.team==='india'?'#fff1bb':'#ff9c7c',transparent:true,opacity:.95})));const missile=new THREE.Mesh(new THREE.SphereGeometry(1.5,8,6),new THREE.MeshBasicMaterial({color:'#fff1cf'}));missile.position.set(p.x,p.altitude,p.y);effects.add(missile);}
 for(const shot of g.shots.filter(s=>s.team==='india'||alive(g,'india').some(u=>Math.hypot(u.x-s.to.x,u.y-s.to.y)<90))){const blast=new THREE.Mesh(new THREE.SphereGeometry((shot.heavy?9:4)*(1+shot.age),12,8),new THREE.MeshBasicMaterial({color:shot.hit?'#ffc17d':'#dbe5e5',transparent:true,opacity:Math.max(0,.65-shot.age*.45),depthWrite:false}));blast.position.copy(drape(shot.to,3));effects.add(blast);}
 for(const a of recentAlerts(g).slice(0,8)){const radius=Math.max(4,Math.min(18,camera.position.distanceTo(drape(a,4))*.035));const points=Array.from({length:49},(_,i)=>drape({x:a.x+Math.cos(i/48*Math.PI*2)*radius,y:a.y+Math.sin(i/48*Math.PI*2)*radius},5));effects.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#ffb17f',depthTest:false})));}
 terrainMat.color.set(q.layers.terrain?'#ffffff':'#8b9b89');contours.visible=q.layers.terrain;obstacleMesh.visible=q.layers.terrain;
 }
 deployment.visible=!!q.placing&&!!hovered;if(q.placing&&hovered){deployment.position.copy(drape(hovered,3));deployment.scale.setScalar((SPECS[q.placing].range?effectiveRange(g,{...hovered,kind:q.placing,team:'india',level:0}):engagementDistance(60))/26);deployment.material.color.set(canPlace(g,hovered,q.placing)?'#f5d598':'#ff807a');}controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(animate);}
 raf=requestAnimationFrame(animate);return()=>{active=false;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();rig.current=null;clearDynamic(paths);clearDynamic(effects);for(const disposable of disposables)disposable.dispose();renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointermove',pointerMove);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointercancel',cancel);renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.dispose();renderer.domElement.remove();};
 },[]);
 return <div className="terrain-view" ref={mount} aria-label="Interactive three-dimensional terrain map">{box&&<div className="drag-selection" style={{left:box.x,top:box.y,width:box.w,height:box.h}}/>}<div className="terrain-caption">3D TERRAIN <span>Elevation relief exaggerated · offline geography</span><small>Drag to pan · Cmd/Ctrl-drag select · right-drag orbit</small></div>{error&&<div className="terrain-error"><p>{error}</p><button onClick={props.onFallback}>Return to command map</button></div>}</div>;
}
