import {coverageMultiplier,passiveMaintenance} from './maintenance.ts';
import {newReport,recordDamage,isInfrastructure,validReport} from './report.ts';
import type {MissionReport} from './report.ts';
import {captureMotion} from './motion.ts';
import {battleAlert,validAlerts} from './alerts.ts';
import type {BattleAlert} from './alerts.ts';
import {movementInMapUnits,tacticalDistance,physicalDistance,engagementDistance,ENGAGEMENT_RANGE_MULTIPLIER} from './world.ts';
import {createTheatre,territoryIncome,forwardSector,gameRoute,groundEdge,theatreTick,civilianImpact,jammed,validTheatre} from './theatre.ts';
import type {Theatre,Formation} from './theatre.ts';
import {elevationAt} from './terrain.ts';
import {ADDITIONAL_AIRFIELDS} from './airfields.ts';
import {INDIA_POLYGONS} from './cartography.ts';
import {SPECS,SCENARIOS,DEFAULT,ROSTER} from './catalog.ts';
import type {Team,Kind,Point,Settings,Scenario,Domain} from './catalog.ts';
import {distance,inPolygon,isLand,valid,route,straight,nearestNavigable} from './navigation.ts';
export * from './catalog.ts';
export {distance,isLand};
export type Unit=Point&{id:number;kind:Kind;team:Team;name:string;hp:number;ammo:number;fuel:number;status:string;order:'hold'|'patrol'|'recon'|'attack'|'return'|'move';destination?:Point;origin?:Point;target?:number;cooldown:number;setup:number;service:number;repairing:boolean;heading:number;home:number;patrol?:Point;path:Point[];level:number;delivered:boolean;pathClock:number;trail:Point[];queue:Point[];groupSpeed?:number;resupplyClock:number;lastDamageAt:number;fastService:boolean;scenarioInfrastructure?:boolean};
export type Contact=Point&{id:number;seen:number;identified:boolean;name:string;kind:Kind;hp:number;heading?:number};
export type GameEvent={time:number;text:string;tone:'info'|'good'|'bad'};
export type Shot={id:number;from:Point;to:Point;age:number;team:Team;hit:boolean;heavy?:boolean};
export type Missile={id:number;from:Point;to:Point;team:Team;target:number;age:number;duration:number;damage:number;source:string;profile?:'cruise'|'interceptor'|'air'|'shell'|'naval';hit?:boolean;sourceId?:number;alerted?:boolean};
export type Zone=Point&{name:string;domain:Domain;control:number};
export type Game={version:2;mapRevision?:number;settings:Settings;time:number;running:boolean;started:boolean;result:null|'victory'|'defeat'|'draw';units:Unit[];credits:number;enemyCredits:number;nextWave:number;wave:number;seed:number;id:number;events:GameEvent[];alerts:BattleAlert[];shots:Shot[];contacts:Record<Team,Record<number,Contact>>;kills:number;losses:number;spent:number;score:Record<Team,number>;aiClock:number;weather:number;captures:number[];zones:Zone[];originalBases:number[];targetIds:number[];escortIds:number[];delivered:number[];discovered:number[];rally:Point;holdTime:number;earned:number;missiles:Missile[];wrecks:(Point&{time:number;sea:boolean})[];built:number;missilesLaunched:number;theatre:Theatre;report:MissionReport};
export const SECTORS=[{x:430,y:235,name:'NORTH'},{x:410,y:385,name:'CENTRAL'},{x:425,y:505,name:'SOUTH'}];
export const alive=(g:Game,t?:Team)=>g.units.filter(u=>u.hp>0&&!u.delivered&&(!t||u.team===t));
export const bases=(g:Game,t:Team)=>alive(g,t).filter(u=>u.kind==='base');
export const operational=(u:Unit)=>u.hp>0&&(u.kind!=='airfield'||u.hp>=SPECS.airfield.hp*(1+u.level*.2)*.35)&&!u.delivered&&u.setup===0&&u.service===0&&u.order!=='move';
export const maxHp=(u:Unit)=>SPECS[u.kind].hp*(1+u.level*.2);
export const formationStrength=(u:Unit)=>Math.max(0,Math.ceil(SPECS[u.kind].members*u.hp/maxHp(u)));
export function random(g:Game){g.seed=(Math.imul(1664525,g.seed)+1013904223)>>>0;return g.seed/4294967296;}
export function event(g:Game,text:string,tone:GameEvent['tone']='info'){g.events.unshift({time:g.time,text,tone});g.events=g.events.slice(0,200);}
export function difficulty(s:Settings):Settings{const base={...DEFAULT,...s};return s.difficulty==='custom'?base:({...base,...({easy:{resources:1.45,activity:.65,damage:.8,forces:3},normal:{resources:1,activity:1,damage:1,forces:2},hard:{resources:.85,activity:1.4,damage:1.15,forces:2}}[s.difficulty])});}
export function add(g:Game,kind:Kind,team:Team,p:Point,name?:string){const s=SPECS[kind],id=++g.id;const home=bases(g,team).sort((a,b)=>distance(a,p)-distance(b,p))[0]?.id??id;const u:Unit={...p,id,kind,team,name:name??`${s.name} ${String(id).padStart(2,'0')}`,hp:s.hp,ammo:s.ammo,fuel:100,status:'Ready',order:'hold',cooldown:0,setup:0,service:0,repairing:false,heading:team==='india'?-90:90,home,path:[],level:0,delivered:false,pathClock:0,trail:[],queue:[],resupplyClock:0,lastDamageAt:g.time,fastService:false};g.units.push(u);return u;}
export function inIndia(p:Point){return INDIA_POLYGONS.some(poly=>inPolygon(p,poly));}
export function income(g:Game,t:Team='india'){const base=alive(g,t).filter(u=>operational(u)&&!u.scenarioInfrastructure).reduce((n,u)=>n+SPECS[u.kind].income*(1+u.level*.4),0);const zone=g.zones.filter(z=>z.domain!=='land'&&(t==='india'?z.control>80:z.control< -80)).length*.4;return (base+zone+territoryIncome(g,t))*(t==='india'&&g.theatre.economyUntil>g.time?.85:1)*(t==='india'?g.settings.resources:1.25*g.settings.activity);}
export function supplied(g:Game,u:Unit){const s=SPECS[u.kind];if(s.structure||s.domain==='land'&&g.theatre.sectors.some(z=>z.connected===u.team&&distance(u,z)<70))return true;return alive(g,u.team).some(b=>{if(!operational(b)||u.id===b.id)return false;const k=b.kind;if(s.sea)return(k==='harbor'||k==='supplyship'||k==='carrier')&&distance(u,b)<190;if(s.air)return(k==='base'||k==='airfield'||k==='carrier')&&distance(u,b)<180;return(['base','depot','logistics','engineer'].includes(k))&&distance(u,b)<(k==='depot'?190:k==='base'?170:120);});}
export function effectiveRange(g:Game,u:Pick<Unit,'kind'|'level'|'x'|'y'|'team'>){const radar=alive(g,u.team).some(r=>r.kind==='radar'&&operational(r)&&distance(r,u)<230);return (SPECS[u.kind].missile?SPECS[u.kind].range*ENGAGEMENT_RANGE_MULTIPLIER:engagementDistance(SPECS[u.kind].range))*coverageMultiplier(u.kind)*(1+u.level*.08)*((u.kind==='s400'||u.kind==='hq9')&&!radar?.78:1);}
export function canPlace(g:Game,p:Point,kind:Kind='s400'){const s=SPECS[kind];if(!valid(p,s.sea?'sea':'land'))return false;if(s.sea){if(kind==='harbor')return p.x>=300&&p.x<=510&&p.y>=590&&p.y<=950;return alive(g,'india').some(u=>(u.kind==='harbor'||u.kind==='carrier')&&operational(u)&&distance(u,p)<190);}
const forward=forwardSector(g,p),sector=g.theatre.sectors.find(s=>Math.abs(p.x-s.x)<=50&&Math.abs(p.y-s.y)<=46);const controlled=sector?sector.connected==='india':inIndia(p)||forward;if(!controlled)return false;if(s.structure)return alive(g,'india').some(u=>(u.kind==='engineer'||u.kind==='base')&&operational(u)&&distance(u,p)<(u.kind==='engineer'?140:180));return forward||alive(g,'india').some(u=>(u.kind==='base'||u.kind==='airfield')&&operational(u)&&distance(u,p)<180);}
export function deploy(g:Game,kind:Kind,p:Point):string|null{if(g.result)return 'Start a new operation to deploy units.';if(!ROSTER.includes(kind))return 'This unit is not available to your command.';if(alive(g,'india').length>=100)return 'Command limit reached: 100 active formations.';const s=SPECS[kind];if(!canPlace(g,p,kind))return s.sea?'Place ships near a friendly anchorage or carrier. Anchorages belong in the marked Arabian Sea area.':s.structure?'Build on friendly land within reach of a command base or engineer.':'Place on friendly land near a completed command base or airfield.';if(alive(g).some(u=>distance(u,p)<tacticalDistance(s.structure?28:15)))return 'Choose a clear position away from another unit.';if(g.credits<s.cost)return `You need ${s.cost} credits.`;g.credits-=s.cost;g.spent+=s.cost;const u=add(g,kind,'india',p);u.setup=g.started?(s.structure?24:8):0;u.status=u.setup?'Deploying':'Ready';if(s.structure)g.built++;event(g,`${u.name} ${s.structure?'construction ordered':'deployed'}.`,'good');detect(g);return null;}
export function suggestedDeployment(g:Game,kind:Kind,near?:Point):Point|null{const centers=alive(g,'india').filter(u=>SPECS[kind].sea?['harbor','carrier'].includes(u.kind):['base','airfield','engineer','bridgelayer'].includes(u.kind)).sort((a,b)=>near?distance(a,near)-distance(b,near):0);for(const c of centers)for(const r of [tacticalDistance(40),tacticalDistance(65),40,65,95,125])for(let n=0;n<12;n++){const p={x:c.x+Math.cos(n*Math.PI/6)*r,y:c.y+Math.sin(n*Math.PI/6)*r};if(canPlace(g,p,kind)&&!alive(g).some(u=>distance(u,p)<tacticalDistance(SPECS[kind].structure?28:15)))return p;}return null;}
export function canHit(u:Unit,v:Pick<Unit,'kind'>){const s=SPECS[u.kind],t=SPECS[v.kind];return s.damage>0&&s.targets.includes(t.domain)&&(!['s400','akash'].includes(u.kind)||t.domain!=='land'||t.damage>0&&!t.structure)&&(!['interceptordrone','counterdrone'].includes(u.kind)||['drone','armeddrone','interceptordrone'].includes(v.kind));}
function setRoute(g:Game,u:Unit,p:Point,order:Unit['order'],target?:number){const r=gameRoute(g,u,p);if(!r)return false;u.order=order;u.destination={...p};u.path=r;u.origin={x:u.x,y:u.y};u.patrol={...p};u.target=target;u.status=order==='attack'?'Engaging':order==='recon'?'Scouting':SPECS[u.kind].sea?'Underway':SPECS[u.kind].air?'On patrol':'Advancing';return true;}
export function command(g:Game,ids:number[],p:Point,order:Unit['order']='patrol',target?:number,append=false,formation:Formation='line'):string|null{
 if(g.result)return 'This operation has ended.';
 if(target&&g.theatre.truceUntil>g.time)return 'A negotiated stand-down is active. Movement and supply orders remain available.';
 const us=alive(g,'india').filter(u=>ids.includes(u.id));if(!us.length)return 'Select a friendly unit first.';
 if(us.some(u=>SPECS[u.kind].speed===0))return 'This installation is fixed. Select mobile formations.';
 if(us.some(u=>u.setup>0||u.service>0))return 'Wait until deployment or service finishes.';
 const c=target?g.contacts.india[target]:null;
 if(target&&(!c||g.time-c.seen>1||!c.identified))return 'Identify a current contact before issuing an engagement order.';
 if(c&&us.some(u=>!canHit(u,c)))return 'One of the selected formations cannot engage this target type.';
 if(us.some(u=>SPECS[u.kind].missile)&&target)return 'Use the cruise launch command for this battery.';
 const center={x:us.reduce((n,u)=>n+u.x,0)/us.length,y:us.reduce((n,u)=>n+u.y,0)/us.length};
 const angle=Math.atan2(p.y-center.y,p.x-center.x),forward={x:Math.cos(angle),y:Math.sin(angle)},side={x:-forward.y,y:forward.x};
 const orders=us.map((u,i)=>{const across=formation==='column'?0:(i-(us.length-1)/2)*tacticalDistance(16);const back=formation==='column'?i*tacticalDistance(18):formation==='wedge'?Math.abs(i-(us.length-1)/2)*tacticalDistance(14):0;
 const dest=target?{...p}:{x:p.x+side.x*across-forward.x*back,y:p.y+side.y*across-forward.y*back};
 const from=append?(u.queue.at(-1)??u.destination??u):u;
 const path=target&&distance(u,dest)<=effectiveRange(g,u)*.9?[]:gameRoute(g,{...u,...from},dest);
 return{u,dest,path};});
 if(orders.some(o=>!o.path))return 'No traversable formation route. Use an open river crossing, send engineers to a marked crossing, or choose a lower pass. Ships need water. Try a smaller group or nearby destination.';
 if(append&&us.some(u=>u.queue.length>=12))return 'A formation can queue up to 12 destinations.';
 for(const {u,dest,path} of orders){u.groupSpeed=Math.min(...us.filter(v=>SPECS[v.kind].domain===SPECS[u.kind].domain).map(v=>SPECS[v.kind].speed));
 if(append&&u.path.length){u.queue.push(dest);if(u.order==='attack'){u.order=SPECS[u.kind].air?order:'move';u.target=undefined;}continue;}
 u.queue=[];u.order=target?(path!.length===0&&['s400','akash','hq9','counterdrone'].includes(u.kind)?'hold':'attack'):SPECS[u.kind].air?order:'move';u.destination=dest;u.path=path!;u.origin={x:u.x,y:u.y};u.patrol={...dest};u.target=target;u.status=target?'Engaging':SPECS[u.kind].sea?'Underway':SPECS[u.kind].air?'On patrol':'Advancing';
 if(path!.length&&['s400','akash','artillery','brahmos','base'].includes(u.kind))u.setup=3;}
 event(g,`${us.length===1?us[0].name:us.length+' formations'}: ${target?'engagement ordered':append?'destination queued':formation+' movement ordered'}.`);return null;
}
export function hold(g:Game,ids:number[]){for(const u of alive(g,'india').filter(u=>ids.includes(u.id))){if(u.path.length&&['s400','akash','artillery','brahmos','base'].includes(u.kind))u.setup=Math.max(u.setup,4);u.order='hold';u.path=[];u.queue=[];u.groupSpeed=undefined;u.destination=undefined;u.target=undefined;u.status='Holding position';}}
export function launch(g:Game,ids:number[],target:number):string|null{if(g.theatre.truceUntil>g.time)return 'Stand-down active: new launches are suspended.';if(g.result)return 'The operation has ended.';const us=alive(g,'india').filter(u=>ids.includes(u.id));if(!us.length||us.some(u=>!SPECS[u.kind].missile))return 'Select a cruise missile battery.';const c=g.contacts.india[target];if(!c||!c.identified||g.time-c.seen>1)return 'A current identified target is required.';for(const u of us){if(!canHit(u,c))return 'Cruise batteries engage fictional ground and naval assets.';if(u.ammo<1)return 'No missiles remaining. Resupply this battery.';if(u.setup||u.service||u.cooldown||u.path.length||u.order!=='hold')return 'Stop and emplace the launcher, then wait for service or cooldown to finish.';if(!supplied(g,u))return 'Reconnect the launcher to the supply network.';if(distance(u,c)>effectiveRange(g,u))return 'Target lies outside the fictional game coverage ring.';}for(const u of us){u.ammo--;u.cooldown=SPECS[u.kind].cooldown;u.order='hold';u.path=[];u.destination=undefined;u.status='Cruise launch';g.missiles.push({id:++g.id,from:{x:u.x,y:u.y},to:{x:c.x,y:c.y},team:u.team,target:c.id,age:0,duration:4+physicalDistance(distance(u,c))/55,damage:SPECS[u.kind].damage,source:u.name,sourceId:u.id,profile:'cruise'});g.missilesLaunched++;}event(g,`${us.length} cruise strike${us.length>1?'s':''} launched at ${c.name}.`);return null;}
export function attackSelected(g:Game,ids:number[],target:number){
 const contact=g.contacts.india[target];
 if(!contact||!contact.identified||g.time-contact.seen>1)return {issued:0,rejected:ids.length,message:'Scout and identify a current contact before attacking.'};
 const units=alive(g,'india').filter(u=>ids.includes(u.id));
 if(!units.length)return {issued:0,rejected:0,message:'Select a friendly formation, then click an enemy.'};
 let issued=0;const reasons:string[]=[];
 for(const u of units){
  let error:string|null=null;
  if(!canHit(u,contact))error='Some selected units cannot engage this target type.';
  else if(!u.ammo)error='Out of ammunition. Resupply before attacking.';
  else error=SPECS[u.kind].missile?launch(g,[u.id],target):command(g,[u.id],contact,'attack',target);
  if(error)reasons.push(error);else issued++;
 }
 return {issued,rejected:reasons.length,message:issued?`${issued} formation${issued===1?'':'s'} attacking ${contact.name}.${reasons.length?' '+reasons[0]:''}`:reasons[0]};
}
export function service(g:Game,ids:number[],repair=false):string|null{if(g.result)return 'The operation has ended.';const us=alive(g,'india').filter(u=>ids.includes(u.id));if(!us.length)return 'Select a friendly unit first.';if(us.some(u=>u.setup||u.service))return 'A selected unit is already deploying or servicing.';if(us.some(u=>!SPECS[u.kind].air&&!supplied(g,u)))return 'Move into supply coverage to service this formation.';const price=us.length*(repair?65:35);if(g.credits<price)return `Service costs ${price} credits.`;g.credits-=price;g.spent+=price;for(const u of us){u.fastService=true;u.repairing=repair;u.target=undefined;u.queue=[];u.groupSpeed=undefined;u.path=[];u.destination=undefined;if(SPECS[u.kind].air){u.order='return';u.status='Returning to base';}else{u.order='hold';u.service=repair?12:9;u.status=repair?'Repairing':'Resupplying';}}event(g,`${repair?'Repair':'Resupply'} order accepted for ${us.length} formation${us.length===1?'':'s'}.`);return null;}
export function upgrade(g:Game,id:number):string|null{const u=alive(g,'india').find(u=>u.id===id);if(!u)return 'Select a friendly unit.';if(g.result||u.setup||u.service)return 'Unit must be ready during an active operation.';if(u.level>=2)return 'Maximum upgrade tier reached.';const cost=Math.round(SPECS[u.kind].cost*.55*(u.level+1));if(g.credits<cost)return `Upgrade requires ${cost} credits.`;g.credits-=cost;g.spent+=cost;u.level++;u.hp=Math.min(maxHp(u),u.hp+SPECS[u.kind].hp*.2);u.setup=10;event(g,`${u.name} upgraded to tier ${u.level+1}.`,'good');return null;}
const LZ=[{x:480,y:320,name:'RIDGE'},{x:465,y:425,name:'CROSSROADS'},{x:480,y:540,name:'BASIN'}];
const NZ=[{x:285,y:700,name:'GATEWAY'},{x:355,y:800,name:'MIDWAY'},{x:350,y:910,name:'SOUTH REACH'}];
export function createGame(input:Settings=DEFAULT):Game{const settings=difficulty(input),sc=SCENARIOS[settings.scenario];const zones=(sc.focus==='navy'?NZ:settings.scenario==='skies'?SECTORS:LZ).map(z=>({...z,domain:(sc.focus==='navy'?'sea':settings.scenario==='skies'?'air':'land') as Domain,control:0}));const g:Game={version:2,mapRevision:5,settings,time:0,running:false,started:false,result:null,units:[],credits:Math.round((settings.scenario==='sandbox'?4500:1250)*settings.resources),enemyCredits:1000,nextWave:40,wave:0,seed:settings.seed>>>0,id:0,events:[],alerts:[],shots:[],contacts:{india:{},pakistan:{}},kills:0,losses:0,spent:0,score:{india:0,pakistan:0},aiClock:0,weather:sc.weather==='night'?.65:sc.weather==='storm'?.75:1,captures:[0,0,0],zones,originalBases:[],targetIds:[],escortIds:[],delivered:[],discovered:[],rally:sc.focus==='navy'?{x:365,y:920}:{x:540,y:615},holdTime:0,earned:0,missiles:[],wrecks:[],built:0,missilesLaunched:0,theatre:createTheatre(),report:newReport()};
for(const [x,y,name]of [[585,285,'Sentinel command'],[545,415,'Trident command'],[535,560,'Meridian command']] as [number,number,string][])g.originalBases.push(add(g,'base','india',{x,y},name).id);
const enemyBases=[];for(const [x,y,name]of [[335,215,'Echo command'],[280,350,'Kestrel command'],[290,480,'Delta command']] as [number,number,string][])enemyBases.push(add(g,'base','pakistan',{x,y},name).id);
add(g,'s400','india',{x:525,y:325},'S-400 · Aegis');add(g,'akash','india',{x:490,y:495},'Akash · Guardian');add(g,'radar','india',{x:575,y:385},'Radar · Watchtower');add(g,'logistics','india',{x:555,y:445},'Supply · Atlas');add(g,'engineer','india',{x:570,y:475},'Engineers · Pioneer');
for(let i=0;i<Math.round(settings.forces*settings.forceScale);i++)add(g,i%2?'tejas':'rafale','india',{x:585+i*13,y:315+i*23});
for(const [kind,p]of [['infantry',{x:515,y:400}],['t90',{x:515,y:455}],['bmp',{x:505,y:525}]] as [Kind,Point][])add(g,kind,'india',p);
add(g,'hq9','pakistan',{x:320,y:310});add(g,'radar','pakistan',{x:345,y:375});add(g,'logistics','pakistan',{x:305,y:430});add(g,'alkhalid','pakistan',{x:385,y:385});add(g,'infantry','pakistan',{x:400,y:445});
for(const [x,y,name]of [[660,345,'Aster airfield'],[615,520,'Copper airfield'],[560,660,'Monarch airfield']] as [number,number,string][])add(g,'airfield','india',{x,y},name);
const airfields=[];for(const [x,y,name]of [[355,250,'Falcon airfield'],[345,420,'Slate airfield'],[275,445,'Cinder airfield']] as [number,number,string][])airfields.push(add(g,'airfield','pakistan',{x,y},name).id);
add(g,'harbor','india',{x:405,y:695},'Sapphire anchorage');add(g,'destroyer','india',{x:395,y:735},'Destroyer · Vanguard');add(g,'frigate','india',{x:435,y:785},'Frigate · Resolve');add(g,'supplyship','india',{x:410,y:815});add(g,'harbor','pakistan',{x:245,y:595},'Obsidian anchorage');add(g,'type054','pakistan',{x:250,y:640});add(g,'agosta','pakistan',{x:295,y:675});
if(['armor','convoy','laststand','joint'].includes(settings.scenario)){add(g,'infantry','india',{x:530,y:365});add(g,'arjun','india',{x:540,y:485});add(g,'artillery','india',{x:570,y:515});}
if(['runway','missileraid','joint','sandbox'].includes(settings.scenario)){add(g,'brahmos','india',{x:590,y:455});add(g,'drone','india',{x:625,y:410});}
if(sc.focus==='navy'){add(g,'submarine','india',{x:380,y:795});add(g,'frigate','india',{x:370,y:760});add(g,'carrier','india',{x:430,y:850});}
if(settings.scenario==='economy'){g.credits=950;add(g,'engineer','india',{x:615,y:470});}
if(settings.scenario==='recon'){add(g,'drone','india',{x:610,y:385});add(g,'drone','india',{x:580,y:505});}
if(settings.scenario==='laststand'){g.units.filter(u=>g.originalBases.slice(0,2).includes(u.id)).forEach(u=>u.hp=0);g.originalBases=g.originalBases.slice(2);g.nextWave=30;}
g.targetIds=settings.scenario==='campaign'?enemyBases:settings.scenario==='runway'||settings.scenario==='recon'?airfields:settings.scenario==='missileraid'||settings.scenario==='joint'?airfields.slice(0,2):[];
if(sc.mode==='escort'){const count=settings.scenario==='convoy'?3:2;for(let i=0;i<count;i++){const p=settings.scenario==='convoy'?{x:550+i*18,y:345}:{x:405+i*30,y:720};g.escortIds.push(add(g,settings.scenario==='convoy'?'logistics':'supplyship','india',p,`Escort ${i+1} · ${settings.scenario==='convoy'?'supply column':'replenishment ship'}`).id);}}
if(settings.forceScale>1){for(let i=0;i<Math.floor(settings.forceScale-1);i++){add(g,'t90','india',{x:615+i*25,y:570});add(g,'infantry','india',{x:615+i*25,y:595});add(g,'frigate','india',{x:350+i*25,y:845});}}
for(const field of ADDITIONAL_AIRFIELDS)add(g,'airfield',field.team,field,field.name);
add(g,'armeddrone','india',{x:610,y:430},'Strike UAV · Kestrel');add(g,'counterdrone','india',{x:565,y:355},'Counter-drone · Umbrella');add(g,'bridgelayer','india',{x:495,y:310},'River engineers · Span');add(g,'counterdrone','pakistan',{x:320,y:395});
for(const u of g.units.filter(u=>['s400','akash','hq9','radar'].includes(u.kind))){const b=bases(g,u.team).sort((a,b)=>distance(a,u)-distance(b,u))[0];if(b){u.x=b.x+tacticalDistance(u.x-b.x);u.y=b.y+tacticalDistance(u.y-b.y);}}
seedInfrastructure(g);
event(g,'Choose a service branch, position your forces, and begin the operation.');detect(g);return g;}
export function detectionRange(g:Game,u:Pick<Unit,'kind'>){return engagementDistance(SPECS[u.kind].vision)*coverageMultiplier(u.kind)*g.weather;}
export function detect(g:Game){for(const team of ['india','pakistan'] as Team[]){const sensors=alive(g,team).filter(u=>!u.setup&&!u.service&&detectionRange(g,u)>0);for(const enemy of alive(g,team==='india'?'pakistan':'india')){const sub=['submarine','agosta'].includes(enemy.kind);const nearest=sensors.reduce((n,u)=>{const antiSub=SPECS[u.kind].sea||u.kind==='drone';return Math.min(n,distance(u,enemy)/(detectionRange(g,u)*(sub?(antiSub?.65:.25):1)));},Infinity);if(!g.settings.fog||nearest<1){const old=g.contacts[team][enemy.id];g.contacts[team][enemy.id]={id:enemy.id,x:enemy.x,y:enemy.y,seen:g.time,identified:!g.settings.fog||nearest<.8||!!old?.identified,name:enemy.name,kind:enemy.kind,hp:enemy.hp,heading:enemy.heading};if(team==='india'&&g.targetIds.includes(enemy.id)&&g.contacts[team][enemy.id].identified&&!g.discovered.includes(enemy.id)){g.discovered.push(enemy.id);event(g,`${enemy.name} identified.`,'good');}}}for(const id of Object.keys(g.contacts[team]))if(g.time-g.contacts[team][+id].seen>22)delete g.contacts[team][+id];}}
export function syncBridges(g:Game){for(const c of g.theatre.crossings){if(!c.open)continue;const existing=g.units.find(u=>u.id===c.assetId);if(existing){if(existing.hp<=0){c.open=false;c.progress=0;}continue;}const u=add(g,'bridge',c.owner??(c.id==='east-span'?'india':'pakistan'),c,c.name+' bridge');u.scenarioInfrastructure=true;c.assetId=u.id;}}
function seedInfrastructure(g:Game){for(const s of g.theatre.sectors){const team=s.root??(s.id==='0-1'?'india':'pakistan');const nearby=g.theatre.civilians.reduce((a,b)=>distance(a,s)<distance(b,s)?a:b);const p={x:s.x+(nearby.x-s.x)*.2,y:s.y+(nearby.y-s.y)*.2};const u=add(g,'industry',team,p,s.name+' military works');u.scenarioInfrastructure=true;}syncBridges(g);}
function kill(g:Game,v:Unit,source:string){if(v.hp>0)return;if(v.kind==='bridge'){const c=g.theatre.crossings.find(c=>c.assetId===v.id);if(c){c.open=false;c.progress=0;c.builder=undefined;event(g,`${c.name} destroyed. Ground traffic must reroute or rebuild.`,'bad');}}g.wrecks.push({x:v.x,y:v.y,time:g.time,sea:SPECS[v.kind].sea});g.wrecks=g.wrecks.slice(-40);if(v.team==='india'){g.losses++;event(g,`${v.name} lost.`,'bad');}else{g.kills++;g.credits+=35;g.earned+=35;event(g,`${v.name} disabled by ${source}. +35 credits`,'good');}for(const t of ['india','pakistan'] as Team[])delete g.contacts[t][v.id];}
function damage(g:Game,v:Unit,amount:number,source:string,combat=true){if(v.hp<=0||v.delivered)return;const dealt=Math.min(v.hp,amount);v.hp=Math.max(0,v.hp-amount);v.lastDamageAt=g.time;if(combat){recordDamage(g,v,dealt);battleAlert(g,v,v.hp?'hit':'lost',dealt);if(isInfrastructure(v))civilianImpact(g,v,true,true);}if(!v.hp)kill(g,v,source);}
function move(g:Game,u:Unit,dt:number){if(!u.path.length)return;const s=SPECS[u.kind],p=u.path[0],d=distance(u,p),height=elevationAt(u),speed=movementInMapUnits(u.groupSpeed??s.speed)*(s.air?g.weather:s.domain==='land'?(height>2500?.5:height>700?.75:1):1)*(jammed(g,u)?.55:1)*(u.level?1.1:1);const step=speed*dt;u.heading=Math.atan2(p.y-u.y,p.x-u.x)*180/Math.PI+90;if(!u.trail.length||distance(u,u.trail[u.trail.length-1])>8){u.trail.push({x:u.x,y:u.y});u.trail=u.trail.slice(-14);}if(d<=step){if(s.domain==='land'&&!groundEdge(g,u,p)){u.path=[];u.queue=[];u.order='hold';u.destination=undefined;u.status='Crossing closed · reroute';return;}u.x=p.x;u.y=p.y;u.path.shift();}else{const next={x:u.x+(p.x-u.x)/d*step,y:u.y+(p.y-u.y)/d*step};if(valid(next,s.domain)&&(s.domain!=='land'||groundEdge(g,u,next))){u.x=next.x;u.y=next.y;}else{u.path=[];u.queue=[];u.destination=undefined;u.status='Route blocked · use an open crossing';u.order='hold';}}}
function ai(g:Game){const sc=SCENARIOS[g.settings.scenario];for(const u of alive(g,'pakistan')){const s=SPECS[u.kind];if(u.setup||u.service||u.order==='return'||s.structure||s.missile)continue;if(s.speed===0)continue;const targets=Object.values(g.contacts.pakistan).filter(c=>c.identified&&g.time-c.seen<1&&canHit(u,c)).sort((a,b)=>distance(a,u)-distance(b,u));if(targets[0]&&u.ammo){const c=targets[0];if(distance(u,c)<effectiveRange(g,u)*.82){u.order='hold';u.path=[];u.target=c.id;}else if(u.target!==c.id||u.path.length===0)setRoute(g,u,c,'attack',c.id);}else if(!u.path.length&&!(s.domain==='land'&&sc.focus==='air')&&!['s400','hq9','radar','logistics','artillery'].includes(u.kind)){const zones=s.sea?NZ:s.air&&sc.focus==='air'?SECTORS:LZ;const p=zones[Math.floor(random(g)*zones.length)];setRoute(g,u,{x:p.x+(random(g)-.5)*25,y:p.y+(random(g)-.5)*25},s.air?'patrol':'move');}}}
function wave(g:Game){const sc=SCENARIOS[g.settings.scenario];if(g.settings.scenario==='laststand'&&g.wave>=6){g.nextWave=Infinity;return;}g.wave++;const limit=Math.min(5,1+Math.floor(g.wave/3));const focus=sc.focus;for(let i=0;i<limit&&alive(g,'pakistan').length<85;i++){let choices:Kind[]=focus==='navy'?['type054','agosta']:focus==='army'||focus==='build'?['alkhalid','infantry','artillery']:focus==='air'?['jf17','f16','j10','armeddrone']:['jf17','alkhalid','infantry','type054','armeddrone','interceptordrone'];const kind=choices[Math.floor(random(g)*choices.length)],s=SPECS[kind];if(g.enemyCredits<s.cost)continue;const home=s.sea?alive(g,'pakistan').find(u=>u.kind==='harbor'):bases(g,'pakistan')[Math.floor(random(g)*Math.max(1,bases(g,'pakistan').length))];if(!home)continue;const p={x:home.x+15+random(g)*20,y:home.y+20+random(g)*20};if(!valid(p,s.domain))continue;g.enemyCredits-=s.cost;const u=add(g,kind,'pakistan',p);const zone=(s.sea?NZ:LZ)[Math.floor(random(g)*3)];setRoute(g,u,{x:zone.x,y:zone.y},s.air?'patrol':'move');}event(g,`Hostile reinforcements: wave ${g.wave}${g.settings.scenario==='laststand'?'/6':''}.`,'bad');g.nextWave=g.time+(g.settings.scenario==='laststand'?65:Math.max(24,64/(g.settings.activity*sc.intensity)-g.wave*1.2))*(g.theatre.activityUntil>g.time?1.4:1);}
function end(g:Game,result:Game['result']){g.result=result;g.running=false;event(g,result==='victory'?'Operation complete. Objectives secured.':result==='draw'?'Exercise concluded.':'Operation ended. Objectives not met.',result==='victory'?'good':'bad');}
export function endExercise(g:Game){if(!g.result)end(g,'draw');}
function objectives(g:Game,dt:number){const sc=SCENARIOS[g.settings.scenario],mode=g.settings.scenario;const originalAlive=g.originalBases.filter(id=>g.units.find(u=>u.id===id)!.hp>0).length;if(originalAlive===0||((mode==='shield'||mode==='monsoon')&&originalAlive<2)){end(g,'defeat');return;}
for(const id of g.escortIds){const u=g.units.find(u=>u.id===id)!;if(u.hp>0&&!u.delivered&&distance(u,g.rally)<tacticalDistance(42)){u.delivered=true;u.path=[];g.delivered.push(id);event(g,`${u.name} reached the rally zone.`,'good');}}
if(sc.mode==='escort'){const viable=g.escortIds.filter(id=>g.units.find(u=>u.id===id)!.hp>0).length;if(viable<sc.goal){end(g,'defeat');return;}if(g.delivered.length>=sc.goal){end(g,'victory');return;}}
const targetsDown=g.targetIds.length>0&&g.targetIds.every(id=>g.units.find(u=>u.id===id)?.hp===0);const occupied=g.zones.filter((z,i)=>z.control>=90&&(z.domain!=='land'||g.theatre.sectors.find(s=>s.id===`${i}-1`)?.connected==='india')).length;
if(mode==='armor')g.holdTime=occupied===g.zones.length?g.holdTime+dt:0;
if(sc.mode==='destroy'&&targetsDown||sc.mode==='recon'&&g.discovered.length>=sc.goal||mode==='armor'&&g.holdTime>=sc.goal||sc.mode==='joint'&&targetsDown&&occupied>=2&&alive(g,'india').some(u=>SPECS[u.kind].sea&&SPECS[u.kind].damage>0)){end(g,'victory');return;}
if(sc.mode==='economy'&&g.earned>=sc.goal&&alive(g,'india').filter(u=>u.kind==='industry'&&!u.scenarioInfrastructure&&operational(u)).length>=2&&bases(g,'india').some(u=>operational(u)&&!g.originalBases.includes(u.id))){end(g,'victory');return;}
if(sc.mode==='control'&&mode!=='armor'&&(g.score.india>=sc.goal||g.score.pakistan>=sc.goal)){end(g,g.score.india>=sc.goal?'victory':'defeat');return;}
if(g.time>=sc.duration+g.theatre.deadlineExtension){end(g,sc.mode==='survive'?'victory':sc.mode==='sandbox'?'draw':sc.mode==='control'&&mode!=='armor'?(g.score.india===g.score.pakistan?'draw':g.score.india>g.score.pakistan?'victory':'defeat'):'defeat');}}
export function tick(g:Game,dt:number){if(!g.running||g.result)return;const sc=SCENARIOS[g.settings.scenario];dt=Math.min(dt,sc.duration+g.theatre.deadlineExtension-g.time);captureMotion(g,dt);g.time+=dt;const earned=income(g)*dt;g.credits=Math.min(99999,g.credits+earned);g.earned+=earned;g.enemyCredits=Math.min(4500,g.enemyCredits+income(g,'pakistan')*dt);g.weather=sc.weather==='storm'?.72:sc.weather==='night'?.64:Math.floor(g.time/160)%3===1?.86:1;g.shots=g.shots.filter(s=>(s.age+=dt)<1.4);g.wrecks=g.wrecks.filter(w=>g.time-w.time<120);detect(g);theatreTick(g,dt);syncBridges(g);if(g.time>=g.nextWave&&g.theatre.truceUntil<=g.time)wave(g);g.aiClock-=dt;if(g.aiClock<=0){g.aiClock=6/g.settings.activity;ai(g);}
for(const m of [...g.missiles]){
 m.age+=dt;
 const target=g.units.find(u=>u.id===m.target),cruise=!m.profile||m.profile==='cruise';
 if(!m.alerted&&m.team==='pakistan'&&target?.team==='india'&&target.hp>0){const t=Math.min(1,m.age/m.duration),p={x:m.from.x+(m.to.x-m.from.x)*t,y:m.from.y+(m.to.y-m.from.y)*t};if(distance(p,target)<detectionRange(g,target)){battleAlert(g,target,'incoming');m.alerted=true;}}
 if(!cruise&&m.profile!=='shell'){const c=g.contacts[m.team][m.target];if(c&&g.time-c.seen<1)m.to={x:c.x,y:c.y};}
 if(m.age<m.duration)continue;
 let intercepted=false;
 if(cruise){
  const defence=alive(g,m.team==='india'?'pakistan':'india').find(u=>['s400','akash','hq9'].includes(u.kind)&&operational(u)&&u.order==='hold'&&!u.cooldown&&u.ammo>0&&supplied(g,u)&&distance(u,m.to)<(u.kind==='hq9'?tacticalDistance(80):effectiveRange(g,u)));
  if(defence){defence.ammo--;defence.cooldown=SPECS[defence.kind].cooldown;intercepted=random(g)<.3;g.shots.push({id:++g.id,from:{x:defence.x,y:defence.y},to:{...m.to},age:0,team:defence.team,hit:intercepted});}
 }
 const hit=!intercepted&&(m.hit??true)&&target&&target.hp>0&&distance(target,m.to)<tacticalDistance(cruise?42:m.profile==='shell'?28:50);
 if(hit)damage(g,target,m.damage*(cruise?g.settings.damage*(.9+random(g)*.2):1),m.source);
 else if(target&&target.hp>0&&m.alerted)battleAlert(g,target,intercepted?'intercepted':'missed');
 g.shots.push({id:++g.id,from:{...m.to},to:{...m.to},age:0,team:m.team,hit:!!hit,heavy:cruise||m.profile==='shell'||m.profile==='naval'});
 if(!intercepted&&!(hit&&target&&isInfrastructure(target)))civilianImpact(g,m.to,cruise||m.profile==='shell'||m.profile==='naval');
 if(cruise)event(g,intercepted?'Cruise strike intercepted.':hit?'Cruise strike impacted the designated installation.':'Cruise strike missed its target.',intercepted||!hit?'bad':'good');
 g.missiles=g.missiles.filter(n=>n.id!==m.id);
}
for(const u of alive(g)){if(u.hp<=0)continue;const s=SPECS[u.kind];passiveMaintenance(g,u,dt);u.cooldown=Math.max(0,u.cooldown-dt);u.pathClock=Math.max(0,u.pathClock-dt);if(u.setup>0){u.setup=Math.max(0,u.setup-dt);if(!u.setup)u.status='Ready';continue;}if(u.service>0){u.service=Math.max(0,u.service-dt);if(!u.service){u.ammo=s.ammo;u.fuel=100;if(u.repairing)u.hp=maxHp(u);u.repairing=false;u.fastService=false;u.resupplyClock=0;u.order='hold';u.status='Ready';}continue;}
if(s.air){if(u.order!=='hold'||u.status==='Engaging')u.fuel=Math.max(0,u.fuel-dt*.2);if((u.fuel<25||s.ammo>0&&u.ammo===0)&&u.order!=='return'){u.order='return';u.target=undefined;u.path=[];u.queue=[];u.groupSpeed=undefined;u.status='Returning to base';}}
if(u.order==='return'){const home=alive(g,u.team).filter(v=>['base','airfield','carrier'].includes(v.kind)&&operational(v)).sort((a,b)=>distance(a,u)-distance(b,u))[0];if(home){if(distance(u,home)<tacticalDistance(8)){u.path=[];if(u.fastService){u.service=12;u.status=u.repairing?'Repairing':'Rearming';}else{u.fuel=Math.min(100,u.fuel+dt*2.2);u.status='Automatic resupply';if(u.fuel>=99&&u.ammo>=s.ammo){u.order='hold';u.status='Ready';}}}else{u.path=[{x:home.x,y:home.y}];move(g,u,dt);}}else u.status='No service base';if(u.fuel<=0)damage(g,u,maxHp(u),'Endurance exhausted',false);continue;}
if(u.order==='attack'&&u.target){const c=g.contacts[u.team][u.target];if(c&&g.time-c.seen<1){if(distance(u,c)<=effectiveRange(g,u)*.85){u.path=[];if(['s400','akash','hq9'].includes(u.kind)){u.order='hold';u.setup=3;}}else if(u.pathClock<=0){const r=gameRoute(g,u,c);if(r)u.path=r;u.pathClock=3;}}else if(!u.path.length){u.order='hold';u.target=undefined;u.status='Contact lost';}}
if(u.path.length){move(g,u,dt);if(/blocked|Crossing closed/.test(u.status))continue;if(!u.path.length&&u.order!=='attack'){if(u.queue.length){const next=u.queue.shift()!;const nextPath=gameRoute(g,u,next);if(nextPath){u.path=nextPath;u.destination=next;u.patrol=next;}else{u.queue=[];u.order='hold';u.destination=undefined;u.status='Queued route blocked';}}else if(s.air&&u.patrol){u.groupSpeed=undefined;const p=u.patrol,angle=random(g)*Math.PI*2;u.path=[{x:p.x+Math.cos(angle)*tacticalDistance(24),y:p.y+Math.sin(angle)*tacticalDistance(24)}];}else{u.groupSpeed=undefined;u.order='hold';u.destination=undefined;u.status='Holding position';if(['s400','akash','artillery','brahmos','base'].includes(u.kind))u.setup=4;}}}
if(g.theatre.truceUntil>g.time||u.setup>0||!s.damage||s.missile||!u.ammo||u.cooldown>0)continue;if(['s400','akash','hq9'].includes(u.kind)&&(u.order!=='hold'||!supplied(g,u))){u.status=u.order!=='hold'?'Relocating':'Supply disconnected';continue;}
const candidates=alive(g,u.team==='india'?'pakistan':'india').filter(v=>{const c=g.contacts[u.team][v.id];return c?.identified&&g.time-c.seen<1&&canHit(u,v)&&distance(u,v)<=effectiveRange(g,u)&&(!s.air||SPECS[v.kind].air||u.order!=='recon');}).sort((a,b)=>(a.id===u.target?-1000:distance(a,u))-(b.id===u.target?-1000:distance(b,u)));
for(const v of candidates.slice(0,Math.min(s.slots,u.ammo))){if(v.hp<=0)continue;battleAlert(g,v,'incoming');u.ammo--;const hit=random(g)<(jammed(g,u)?.42:.8);g.shots.push({id:++g.id,from:{x:u.x,y:u.y},to:{x:v.x,y:v.y},age:0,team:u.team,hit,heavy:s.damage>40});const amount=s.damage*g.settings.damage*(.85+random(g)*.3)*(.65+.35*u.hp/maxHp(u))*(1+u.level*.12);
 const profile:Missile['profile']=['s400','akash','hq9'].includes(u.kind)?'interceptor':s.air?'air':u.kind==='artillery'?'shell':s.sea?'naval':undefined;
 if(profile){g.shots.pop();g.missiles.push({id:++g.id,from:{x:u.x,y:u.y},to:{x:v.x,y:v.y},age:0,duration:Math.max(.8,Math.min(3.6,physicalDistance(distance(u,v))/(profile==='shell'?48:95)+.7)),team:u.team,target:v.id,damage:amount,source:u.name,sourceId:u.id,profile,hit,alerted:v.team==='india'});}
 else if(hit){damage(g,v,amount,u.name);if(!isInfrastructure(v))civilianImpact(g,v,false);}else battleAlert(g,v,'missed');}if(candidates.length){u.cooldown=s.cooldown;u.status='Engaging';}else if(!u.path.length&&!/blocked|Crossing closed/.test(u.status))u.status=u.ammo?'Ready':'Out of ammunition';}
for(const z of g.zones){if(z.domain==='land')continue;const count=(team:Team)=>alive(g,team).filter(u=>!u.setup&&!u.service&&SPECS[u.kind].domain===z.domain&&(z.domain==='air'||SPECS[u.kind].capture)&&distance(u,z)<tacticalDistance(60)).length;const own=count('india'),foe=count('pakistan');z.control=Math.max(-100,Math.min(100,z.control+(own>foe?1:foe>own?-1:0)*dt*5));if(z.control>80&&!foe)g.score.india+=dt*.6;if(z.control< -80&&!own)g.score.pakistan+=dt*.6;}
g.captures=g.zones.map(z=>z.control);objectives(g,dt);}
export function objectiveProgress(g:Game){const s=SCENARIOS[g.settings.scenario];if(s.mode==='escort')return `${g.delivered.length}/${s.goal} escorted`;if(s.mode==='destroy')return `${g.targetIds.filter(id=>g.units.find(u=>u.id===id)?.hp===0).length}/${g.targetIds.length} targets disabled`;if(s.mode==='recon')return `${g.discovered.length}/${s.goal} sites identified`;if(s.mode==='economy')return `${Math.floor(g.earned)}/${s.goal} credits earned`;if(g.settings.scenario==='armor')return `${Math.floor(g.holdTime)}/45 seconds holding all sectors`;if(s.mode==='control')return `${Math.floor(g.score.india)}/${s.goal} control points`;if(s.mode==='joint')return `${g.zones.filter((z,i)=>z.control>=90&&g.theatre.sectors.find(s=>s.id===`${i}-1`)?.connected==='india').length}/2 sectors · ${g.targetIds.filter(id=>g.units.find(u=>u.id===id)?.hp===0).length}/2 airfields`;return `${g.originalBases.filter(id=>g.units.find(u=>u.id===id)?.hp!>0).length}/${g.originalBases.length} original command posts`;}
export function deserialize(raw:string):Game|null {
  try {
    const data=JSON.parse(raw);
    if(![1,2].includes(data?.version)||!Array.isArray(data.units)||!SCENARIOS[data.settings?.scenario as Scenario]||!Number.isFinite(data.time)||!data.contacts?.india||!data.contacts?.pakistan||!Array.isArray(data.events)||!data.score) return null;
    // The first release only saved these three operations. Reject invented legacy missions.
    if(data.version===1&&!['shield','skies','campaign'].includes(data.settings.scenario))return null;
    const point=(p:Point)=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y);
    const points=(p:Point[])=>Array.isArray(p)&&p.every(point);
    if(data.units.some((u:Unit)=>!SPECS[u.kind]||!['india','pakistan'].includes(u.team)||!Number.isInteger(u.id)||![u.x,u.y,u.hp,u.ammo,u.fuel,u.cooldown,u.setup,u.service].every(Number.isFinite)))return null;
    const settings:Settings={...DEFAULT,...data.settings};
    if(!['easy','normal','hard','custom'].includes(settings.difficulty)||![settings.seed,settings.resources,settings.activity,settings.damage,settings.forces,settings.forceScale].every(Number.isFinite)||settings.activity<=0||settings.forceScale<=0)return null;
    const fresh=createGame(settings);
    if(data.alerts!==undefined&&!validAlerts(data.alerts))return null;
    if(data.report!==undefined&&!validReport(data.report))return null;
    if(data.units.some((u:Unit)=>[u.resupplyClock,u.lastDamageAt].some(n=>n!==undefined&&(!Number.isFinite(n)||n<0))))return null;
    const g={...fresh,...data,report:data.report??newReport(data.time),alerts:data.alerts??[],version:2,mapRevision:5,settings,running:false} as Game;
    g.units=data.units.map((u:Unit)=>({...u,resupplyClock:u.resupplyClock??0,lastDamageAt:u.lastDamageAt??data.time,fastService:u.fastService===undefined?!!u.repairing&&u.order==='return':!!u.fastService,path:points(u.path)?u.path:data.version===1&&point(u.destination!)?route(u,u.destination!,SPECS[u.kind].domain)??[]:[],trail:points(u.trail)?u.trail:[],queue:points(u.queue)?u.queue:[],groupSpeed:Number.isFinite(u.groupSpeed)&&u.groupSpeed!>0?u.groupSpeed:undefined,level:Number.isInteger(u.level)&&u.level>=0&&u.level<=2?u.level:0,delivered:!!u.delivered,pathClock:Number.isFinite(u.pathClock)?u.pathClock:0}));
    if(data.theatre&&!validTheatre(data.theatre))return null;
    g.theatre=data.theatre??createTheatre();
    if(new Set(g.units.map(u=>u.id)).size!==g.units.length)return null;
    if(data.version===1){
      g.originalBases=g.units.filter(u=>u.team==='india'&&u.kind==='base').map(u=>u.id);
      g.targetIds=g.settings.scenario==='campaign'?g.units.filter(u=>u.team==='pakistan'&&u.kind==='base').map(u=>u.id):[];
      g.zones=fresh.zones.map((z,i)=>({...z,control:Number.isFinite(data.captures?.[i])?data.captures[i]:0}));
      g.missiles=[];
    }
    for(const name of ['originalBases','targetIds','escortIds','delivered','discovered'] as const){
      if(!Array.isArray(g[name])||g[name].some(id=>!g.units.some(u=>u.id===id)))return null;
    }
    if(!g.originalBases.length||g.originalBases.some(id=>!g.units.some(u=>u.id===id&&u.kind==='base'&&u.team==='india')))return null;
    const mode=SCENARIOS[settings.scenario].mode;
    if(['destroy','recon','joint'].includes(mode)&&!g.targetIds.length||mode==='escort'&&g.escortIds.length<SCENARIOS[settings.scenario].goal)return null;
    if(!Array.isArray(g.zones)||g.zones.some(z=>!point(z)||!Number.isFinite(z.control)||!['land','air','sea'].includes(z.domain)))return null;
    if(!Array.isArray(g.missiles)||g.missiles.some(m=>!point(m.from)||!point(m.to)||![m.id,m.target,m.age,m.duration,m.damage].every(Number.isFinite)||m.duration<=0))return null;
    if(!Array.isArray(g.shots)||g.shots.some(s=>!point(s.from)||!point(s.to)||!Number.isFinite(s.age)))return null;
    if(!Array.isArray(g.wrecks)||g.wrecks.some(w=>!point(w)||!Number.isFinite(w.time)))return null;
    for(const team of ['india','pakistan'] as const)if(Object.values(g.contacts[team]).some(c=>!point(c)||!SPECS[c.kind]||!Number.isFinite(c.seen)))return null;
    if(![g.credits,g.enemyCredits,g.seed,g.id,g.wave,g.aiClock,g.kills,g.losses,g.spent,g.score.india,g.score.pakistan,g.holdTime,g.earned,g.built,g.missilesLaunched].every(Number.isFinite)||!point(g.rally)||![null,'victory','defeat','draw'].includes(g.result))return null;
    g.nextWave=Number.isFinite(g.nextWave)?g.nextWave:settings.scenario==='laststand'&&g.wave>=6?Infinity:g.time+40;
    g.id=Math.max(g.id,...g.units.map(u=>u.id),...g.missiles.map(m=>m.id),...g.alerts.map(a=>a.id));
    if(data.mapRevision!==5){for(const u of g.units){if(u.hp<=0||u.delivered||valid(u,SPECS[u.kind].domain))continue;const p=nearestNavigable(u,SPECS[u.kind].domain);if(!p)return null;u.x=p.x;u.y=p.y;u.path=[];u.queue=[];u.destination=undefined;u.target=undefined;u.order='hold';u.status='Coastline updated · ready for orders';}}
    g.mapRevision=5;
    if(g.theatre.crossings.some(c=>c.assetId!==undefined&&!g.units.some(u=>u.id===c.assetId&&u.kind==='bridge')))return null;
    for(const c of g.theatre.crossings){if(c.assetId!==undefined&&g.units.find(u=>u.id===c.assetId)!.hp<=0){c.open=false;c.progress=0;}if(data.report!==undefined&&c.open&&c.assetId===undefined)return null;}
    if(data.report===undefined)seedInfrastructure(g);
    return g;
  }catch{return null;}
}
