import {tacticalDistance} from './world.ts';
import type {Game,Unit} from './engine.ts';
import {SPECS} from './catalog.ts';
import type {Point,Team} from './catalog.ts';
import {distance,route} from './navigation.ts';
import {BARRIER_SEGMENTS,segmentIntersection,elevationAt} from './terrain.ts';
export type Formation='line'|'column'|'wedge';
export type Sector=Point&{id:string;name:string;control:number;links:string[];root?:Team;connected:Team|null};
export type Crossing=Point&{id:string;name:string;open:boolean;progress:number;builder?:number;assetId?:number;owner?:Team};
export type CivilianCenter=Point&{id:string;name:string;panic:number;shelter:number;reliefUntil:number;protected:boolean};
export type Offer={id:number;kind:'truce'|'inspection'|'relief';expires:number};
export type Theatre={sectors:Sector[];crossings:Crossing[];civilians:CivilianCenter[];groups:Record<string,number[]>;offer:Offer|null;offerNumber:number;nextOffer:number;truceUntil:number;deadlineExtension:number;economyUntil:number;activityUntil:number;reliefStock:number;reliefClock:number;history:{time:number;text:string}[];captureClock:number};
export const DIPLOMACY={
 truce:{title:'A pause in hostilities',text:'The fictional Meridian delegation proposes a 35-second stand-down.',accept:'No new attacks or reinforcements for 35s. Movement and supply continue. The mission deadline extends by 35s. In-flight weapons finish their flight.',reject:'Fighting continues. The next reinforcement wave arrives up to 12 seconds earlier.'},
 inspection:{title:'Monitored de-escalation',text:'The fictional Horizon commission offers a temporary supply-monitoring agreement.',accept:'Your income is reduced by 15% for 90s. Enemy reinforcement intervals are 40% longer for 90s.',reject:'Keep full income. The opponent receives 120 reinforcement credits.'},
 relief:{title:'Humanitarian corridor',text:'The fictional Lantern mission offers shelter supplies and evacuation support.',accept:'Gain 2 relief packs. Panic falls by 20 at every centre. This does not alter military objectives.',reject:'No supplies arrive. Panic rises by 8 at each centre. This does not alter military objectives.'}
};
const living=(g:Game,t?:Team)=>g.units.filter(u=>u.hp>0&&!u.delivered&&(!t||u.team===t));
const log=(g:Game,text:string,tone:'good'|'info'|'bad'='info')=>{g.events.unshift({time:g.time,text,tone});g.events=g.events.slice(0,200);};
function onRiver(p:Point,name:string){let best=p,d=Infinity;for(const s of BARRIER_SEGMENTS.filter(s=>s.name===name)){const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,k=Math.max(0,Math.min(1,((p.x-s.a.x)*dx+(p.y-s.a.y)*dy)/(dx*dx+dy*dy||1))),q={x:s.a.x+k*dx,y:s.a.y+k*dy};if(distance(p,q)<d){best=q;d=distance(p,q);}}return best;}
export function createTheatre():Theatre{const sectors:Sector[]=[];const rows=[{x:480,y:320,name:'Ridge'},{x:465,y:425,name:'Crossroads'},{x:480,y:540,name:'Basin'}];for(let r=0;r<3;r++)for(let c=0;c<3;c++){sectors.push({id:`${r}-${c}`,name:`${rows[r].name} ${['West','Centre','East'][c]}`,x:rows[r].x+(c-1)*105,y:rows[r].y,control:c===0?-100:c===2?100:0,root:c===0?'pakistan':c===2?'india':undefined,connected:c===0?'pakistan':c===2?'india':null,links:[[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([a,b])=>a>=0&&a<3&&b>=0&&b<3).map(([a,b])=>`${a}-${b}`)});}return {sectors,crossings:[{id:'east-span',name:'Sutlej · East crossing',...onRiver({x:540,y:254},'Sutlej'),open:true,progress:100},{id:'river-gate',name:'Sutlej · River gate',...onRiver({x:419,y:300},'Sutlej'),open:false,progress:0},{id:'north-span',name:'Chenab · North crossing',...onRiver({x:440,y:226},'Chenab'),open:false,progress:0},{id:'indus-mid',name:'Indus · Middle crossing',...onRiver({x:357,y:290},'Indus'),open:false,progress:0},{id:'indus-south',name:'Indus · South crossing',...onRiver({x:262,y:419},'Indus'),open:true,progress:100}],civilians:[{id:'willow',name:'Willow shelter',x:580,y:430},{id:'meadow',name:'Meadow settlement',x:535,y:350},{id:'orchard',name:'Orchard shelter',x:395,y:405},{id:'haven',name:'Haven community',x:320,y:470},{id:'coast',name:'Coastal refuge',x:490,y:665}].map(c=>({...c,panic:0,shelter:100,reliefUntil:0,protected:false})),groups:{},offer:null,offerNumber:0,nextOffer:75,truceUntil:0,deadlineExtension:0,economyUntil:0,activityUntil:0,reliefStock:3,reliefClock:0,history:[],captureClock:0};}
export function reconnect(t:Theatre){for(const s of t.sectors)s.connected=null;for(const team of ['india','pakistan'] as Team[]){const own=(s:Sector)=>team==='india'?s.control>=80:s.control<=-80;const queue=t.sectors.filter(s=>s.root===team&&own(s));for(const s of queue)s.connected=team;for(let i=0;i<queue.length;i++)for(const id of queue[i].links){const next=t.sectors.find(s=>s.id===id);if(next&&next.connected!==team&&own(next)){next.connected=team;queue.push(next);}}}}
export const territoryIncome=(g:Game,t:Team)=>g.theatre.sectors.filter(s=>s.connected===t&&s.root!==t).length*.65;
export const forwardSector=(g:Game,p:Point)=>g.theatre.sectors.some(s=>s.connected==='india'&&distance(s,p)<65);
export function groundEdge(g:Game,a:Point,b:Point){const steps=Math.max(1,Math.ceil(distance(a,b)/8));for(let i=1;i<=steps;i++)if(elevationAt({x:a.x+(b.x-a.x)*i/steps,y:a.y+(b.y-a.y)*i/steps})>5100)return false;for(const s of BARRIER_SEGMENTS){const cross=segmentIntersection(a,b,s.a,s.b);if(cross&&!g.theatre.crossings.some(c=>c.open&&distance(c,cross)<23))return false;}return true;}
export const gameRoute=(g:Game,u:Pick<Unit,'kind'|'x'|'y'>,p:Point)=>route(u,p,SPECS[u.kind].domain,SPECS[u.kind].domain==='land'?(a,b)=>groundEdge(g,a,b):undefined);
export function buildCrossing(g:Game,id:string,ids:number[]):string|null{const c=g.theatre.crossings.find(c=>c.id===id);if(g.result)return 'This operation has ended.';if(!c)return 'Choose a marked river crossing.';if(c.open)return 'This crossing is already open.';if(c.builder)return 'Engineers are already working at this crossing.';const u=living(g,'india').find(u=>ids.includes(u.id)&&['engineer','bridgelayer'].includes(u.kind)&&!u.setup&&!u.service&&!g.theatre.crossings.some(span=>span.builder===u.id)&&distance(u,c)<85);if(!u)return 'Select available engineers within 85 game units. Each formation can build one crossing at a time.';if(g.credits<120)return 'A pontoon crossing costs 120 credits.';g.credits-=120;g.spent+=120;c.builder=u.id;c.progress=0;u.path=[];u.queue=[];u.order='hold';u.target=undefined;u.status='Building pontoon crossing';log(g,`${u.name}: constructing ${c.name}.`);return null;}
export function dispatchRelief(g:Game,id:string):string|null{const c=g.theatre.civilians.find(c=>c.id===id);if(g.result)return 'This operation has ended.';if(!c)return 'Choose a community.';if(c.reliefUntil>g.time)return 'Relief teams are already working here.';if(!g.theatre.reliefStock)return 'No relief packs available. A new pack arrives every 120 simulation seconds.';g.theatre.reliefStock--;c.reliefUntil=g.time+50;c.panic=Math.max(0,c.panic-15);log(g,`Relief dispatched to ${c.name}. Humanitarian report updated.`,'good');return null;}
export function civilianImpact(g:Game,p:Point,heavy=false,infrastructure=false){for(const c of g.theatre.civilians){const d=distance(c,p);const radius=infrastructure?180:tacticalDistance(heavy?95:55);if(d<radius){const amount=(heavy?18:5)*(1-d/radius);const old=c.panic;c.panic=Math.min(100,c.panic+amount);if(g.report){g.report.panicGenerated+=c.panic-old;g.report.peakPanic=Math.max(g.report.peakPanic,c.panic);if(c.panic>old&&!g.report.affectedCenters.includes(c.id))g.report.affectedCenters.push(c.id);}c.shelter=Math.max(0,c.shelter-amount*.35);if(old<40&&c.panic>=40)log(g,`Panic rising near ${c.name}. Move protection or dispatch relief.`,'bad');}}}
export function resolveDiplomacy(g:Game,accept:boolean):string|null{const t=g.theatre,o=t.offer;if(!o)return 'There is no pending diplomatic offer.';if(g.result)return 'This operation has ended.';if(o.kind==='truce'){if(accept){t.truceUntil=g.time+35;t.deadlineExtension+=35;g.nextWave+=35;}else g.nextWave=Math.max(g.time+5,g.nextWave-12);}else if(o.kind==='inspection'){if(accept){t.economyUntil=g.time+90;t.activityUntil=g.time+90;g.nextWave+=20;}else g.enemyCredits+=120;}else{if(accept)t.reliefStock=Math.min(8,t.reliefStock+2);for(const c of t.civilians)c.panic=Math.max(0,Math.min(100,c.panic+(accept?-20:8)));}const text=`${DIPLOMACY[o.kind].title}: ${accept?'accepted':'declined'}.`;t.history.unshift({time:g.time,text});t.history=t.history.slice(0,30);log(g,text,accept?'good':'info');t.offer=null;t.nextOffer=g.time+125;return null;}
export function assignGroup(g:Game,n:number,ids:number[]){const valid=living(g,'india').filter(u=>ids.includes(u.id)).map(u=>u.id);if(n>=1&&n<=9&&valid.length){g.theatre.groups[String(n)]=valid;return `${valid.length} formations assigned to group ${n}.`;}return 'Select formations before assigning a group.';}
export function recallGroup(g:Game,n:number){return(g.theatre.groups[String(n)]??[]).filter(id=>living(g,'india').some(u=>u.id===id));}
export const jammed=(g:Game,u:Unit)=>['drone','armeddrone','interceptordrone'].includes(u.kind)&&living(g,u.team==='india'?'pakistan':'india').some(e=>e.kind==='counterdrone'&&!e.setup&&!e.service&&e.ammo>0&&distance(e,u)<tacticalDistance(SPECS.counterdrone.range));
export function theatreTick(g:Game,dt:number){const t=g.theatre;for(const c of t.crossings){if(c.open||!c.builder)continue;const u=living(g).find(u=>u.id===c.builder);if(!u){c.builder=undefined;log(g,`${c.name}: construction interrupted.`,'bad');continue;}if(distance(u,c)>85||u.path.length||u.setup||u.service)continue;u.status='Building pontoon crossing';c.progress=Math.min(100,c.progress+dt*(u.kind==='bridgelayer'?4:2.5));if(c.progress===100){c.open=true;c.owner=u.team;c.assetId=undefined;c.builder=undefined;log(g,`${c.name} is open to ground formations.`,'good');}}
for(const c of t.civilians){c.protected=living(g).some(u=>SPECS[u.kind].domain==='land'&&!SPECS[u.kind].structure&&!u.setup&&distance(u,c)<tacticalDistance(70));const relief=c.reliefUntil>g.time;c.panic=Math.max(0,c.panic-dt*(relief?.8:c.protected?.24:.035));if(relief)c.shelter=Math.min(100,c.shelter+dt*.7);}t.reliefClock+=dt;if(t.reliefClock>=120){t.reliefClock-=120;t.reliefStock=Math.min(8,t.reliefStock+1);}if(!t.offer&&g.time>=t.nextOffer){t.offer={id:++t.offerNumber,kind:(['truce','inspection','relief'] as const)[(t.offerNumber-1)%3],expires:g.time+55};log(g,`Diplomatic message: ${DIPLOMACY[t.offer.kind].title}.`);}if(t.offer&&g.time>=t.offer.expires){log(g,'Diplomatic offer expired; decline consequences apply.');resolveDiplomacy(g,false);}
// Land objectives and the front-line graph share the central three sectors.
for(let i=0;i<g.zones.length;i++)if(g.zones[i].domain==='land'){const s=t.sectors.find(s=>s.id===`${i}-1`);if(s)s.control=g.zones[i].control;}
reconnect(t);for(const s of t.sectors){const count=(team:Team)=>living(g,team).filter(u=>!u.setup&&!u.service&&SPECS[u.kind].domain==='land'&&SPECS[u.kind].capture&&distance(u,s)<tacticalDistance(58)).length;const own=count('india'),foe=count('pakistan'),team=own>foe?'india':foe>own?'pakistan':null;if(!team)continue;const connected=s.connected===team||s.root===team||s.links.some(id=>t.sectors.find(n=>n.id===id)?.connected===team);if(!connected)continue;const previous=s.control;s.control=Math.max(-100,Math.min(100,s.control+(team==='india'?1:-1)*dt*5));if(previous<80&&s.control>=80||previous>-80&&s.control<=-80)log(g,`${s.name} secured by ${team==='india'?'your forces':'opposing forces'}.`,team==='india'?'good':'bad');}
reconnect(t);for(let i=0;i<g.zones.length;i++)if(g.zones[i].domain==='land')g.zones[i].control=t.sectors.find(s=>s.id===`${i}-1`)!.control;
}
export function validTheatre(t:Theatre):boolean{const point=(p:Point)=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y);return !!t&&Array.isArray(t.sectors)&&t.sectors.length===9&&new Set(t.sectors.map(s=>s.id)).size===9&&t.sectors.every(s=>/^[0-2]-[0-2]$/.test(s.id))&&t.sectors.every(s=>point(s)&&Number.isFinite(s.control)&&Array.isArray(s.links)&&s.links.every(id=>t.sectors.some(n=>n.id===id)))&&Array.isArray(t.crossings)&&t.crossings.length===5&&t.crossings.every(c=>point(c)&&Number.isFinite(c.progress)&&typeof c.open==='boolean'&&(c.assetId===undefined||Number.isInteger(c.assetId))&&(c.owner===undefined||['india','pakistan'].includes(c.owner)))&&Array.isArray(t.civilians)&&t.civilians.length===5&&t.civilians.every(c=>point(c)&&[c.panic,c.shelter,c.reliefUntil].every(Number.isFinite))&&!!t.groups&&Object.values(t.groups).every(ids=>Array.isArray(ids)&&ids.every(Number.isInteger))&&[t.nextOffer,t.offerNumber,t.truceUntil,t.deadlineExtension,t.economyUntil,t.activityUntil,t.reliefStock,t.reliefClock].every(Number.isFinite)&&(!t.offer||!!DIPLOMACY[t.offer.kind]&&[t.offer.id,t.offer.expires].every(Number.isFinite))&&Array.isArray(t.history);}
